FROM registry.access.redhat.com/ubi8/ubi-minimal

ENV PORT 8080
EXPOSE 8080
WORKDIR /usr/src/app

USER 0
RUN microdnf install python38 python3-virtualenv \
    && microdnf clean all

ENV VIRTUAL_ENV=/opt/venv
RUN python3 -m virtualenv --python=/usr/bin/python3 $VIRTUAL_ENV
ENV PATH="$VIRTUAL_ENV/bin:$PATH"

COPY quotegen /usr/src/app/quotegen
COPY pypi /tmp/pypi
RUN chown -R 1001:0 ${VIRTUAL_ENV} && \
    chown -R 1001:0 /usr/src/app/quotegen && \
    chown -R 1001:0 /tmp/pypi
    
USER 1001

WORKDIR /usr/src/app/quotegen
RUN pip install -U pip wheel && \
    pip install --no-index --find-links=/tmp/pypi --no-cache-dir -r requirements.txt && \
    rm -rf /tmp/pypi

CMD [ "python", "app.py"]
